#!/bin/bash

# Install python packages
echo "Installing python packages..."
cd ./py || exit

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  ./venv/bin/python3 -m pip install -r requirements.txt
elif [[ "$OSTYPE" == "darwin"* ]]; then
  ./venv/bin/python3 -m pip install -r requirements.txt
elif [[ "$OSTYPE" == "cygwin" ]]; then
  ./venv/scripts/python.exe -m pip install -r requirements.txt
elif [[ "$OSTYPE" == "msys" ]]; then
  ./venv/scripts/python.exe -m pip install -r requirements.txt
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  ./venv/bin/python3 -m pip install -r requirements.txt
else
  echo "Not sure which OS this is!"
  exit
fi

echo "Done!"

# Install npm packages
echo "Installing npm packages..."
cd ../js || exit
npm install
echo "Done!"