#!/bin/bash

# Install python packages
echo "Installing python packages..."
cd ./py || exit
./venv/bin/python3 -m pip install -r requirements.txt
echo "Done!"

# Install npm packages
echo "Installing npm packages..."
cd ../js || exit
npm install
echo "Done!"