#!/bin/bash

# make sure the script exits when fail
set -e

# start backend
cd ./py || exit
/bin/bash -c "venv/bin/uvicorn main:app --reload"
UVICORN_BASH_PID=$!
cd .. || exit
echo "[BACKEND] Started websocket server..."

# start frontend
cd ./js || exit
bash -c "npm run dev"
NPM_BASH_PID=$!
echo "[FRONTEND] Started GUI application..."

sleep 0.5
xdg-open http://localhost:4173/

trap 'echo "Killing all associated processes..."; kill $NPM_PID; exit' INT

read -r -d '' _ </dev/tty